// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Cast struct {
	ID          int32          `json:"id"`
	MovieID     sql.NullInt32  `json:"movie_id"`
	Name        sql.NullString `json:"name"`
	EnName      sql.NullString `json:"en_name"`
	Profession  sql.NullString `json:"profession"`
	Description sql.NullString `json:"description"`
}

type Genre struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}

type Movie struct {
	ID          int32          `json:"id"`
	RuName      sql.NullString `json:"ru_name"`
	EnName      sql.NullString `json:"en_name"`
	MovieType   sql.NullString `json:"movie_type"`
	Year        sql.NullInt32  `json:"year"`
	Description sql.NullString `json:"description"`
	Top250      sql.NullInt32  `json:"top250"`
	Budget      sql.NullInt32  `json:"budget"`
	Revenue     sql.NullInt32  `json:"revenue"`
	TmdbID      sql.NullInt32  `json:"tmdb_id"`
	KpID        sql.NullInt32  `json:"kp_id"`
}

type MovieGenre struct {
	MovieID int32 `json:"movie_id"`
	GenreID int32 `json:"genre_id"`
}

type Rating struct {
	ID                 int32           `json:"id"`
	MovieID            sql.NullInt32   `json:"movie_id"`
	Kp                 sql.NullFloat64 `json:"kp"`
	Tmdb               sql.NullFloat64 `json:"tmdb"`
	FilmCritic         sql.NullFloat64 `json:"film_critic"`
	RussianFilmCritics sql.NullFloat64 `json:"russian_film_critics"`
}
