// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sqlc.query.sql

package repository

import (
	"context"
	"database/sql"
)

const getCast = `-- name: GetCast :many
SELECT
    id,
    movie_id,
    name,
    en_name,
    profession,
    description
FROM casts
WHERE movie_id = $1
`

func (q *Queries) GetCast(ctx context.Context, movieID sql.NullInt32) ([]Cast, error) {
	rows, err := q.db.QueryContext(ctx, getCast, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cast
	for rows.Next() {
		var i Cast
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Name,
			&i.EnName,
			&i.Profession,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenreByName = `-- name: GetGenreByName :one
SELECT id FROM genres
WHERE name = $1
`

func (q *Queries) GetGenreByName(ctx context.Context, name sql.NullString) (int32, error) {
	row := q.db.QueryRowContext(ctx, getGenreByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getGenres = `-- name: GetGenres :many
SELECT
    g.id,
    g.name
FROM movie_genres mg
JOIN genres g
ON g.id = mg.genre_id
WHERE mg.movie_id = $1
`

func (q *Queries) GetGenres(ctx context.Context, movieID int32) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, getGenres, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListMovies = `-- name: GetListMovies :many
SELECT
    mv.id,
    mv.kp_id,
    mv.ru_name,
    mv.en_name,
    mv.movie_type,
    mv.tmdb_id,
    mv.year,
    rs.kp,
    rs.tmdb
FROM movies mv
LEFT JOIN ratings rs
ON mv.id = rs.movie_id
`

type GetListMoviesRow struct {
	ID        int32           `json:"id"`
	KpID      sql.NullInt32   `json:"kp_id"`
	RuName    sql.NullString  `json:"ru_name"`
	EnName    sql.NullString  `json:"en_name"`
	MovieType sql.NullString  `json:"movie_type"`
	TmdbID    sql.NullInt32   `json:"tmdb_id"`
	Year      sql.NullInt32   `json:"year"`
	Kp        sql.NullFloat64 `json:"kp"`
	Tmdb      sql.NullFloat64 `json:"tmdb"`
}

func (q *Queries) GetListMovies(ctx context.Context) ([]GetListMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, getListMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListMoviesRow
	for rows.Next() {
		var i GetListMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.KpID,
			&i.RuName,
			&i.EnName,
			&i.MovieType,
			&i.TmdbID,
			&i.Year,
			&i.Kp,
			&i.Tmdb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovie = `-- name: GetMovie :one
SELECT
    mv.kp_id,
    mv.id,
    mv.ru_name,
    mv.en_name,
    mv.movie_type,
    mv.description,
    mv.top250,
    mv.budget,
    mv.revenue,
    mv.tmdb_id,
    mv.year,
    rs.kp,
    rs.tmdb,
    rs.film_critic,
    rs.russian_film_critics
FROM movies mv
LEFT JOIN ratings rs
ON mv.id = rs.movie_id
WHERE mv.kp_id = $1
`

type GetMovieRow struct {
	KpID               sql.NullInt32   `json:"kp_id"`
	ID                 int32           `json:"id"`
	RuName             sql.NullString  `json:"ru_name"`
	EnName             sql.NullString  `json:"en_name"`
	MovieType          sql.NullString  `json:"movie_type"`
	Description        sql.NullString  `json:"description"`
	Top250             sql.NullInt32   `json:"top250"`
	Budget             sql.NullInt32   `json:"budget"`
	Revenue            sql.NullInt32   `json:"revenue"`
	TmdbID             sql.NullInt32   `json:"tmdb_id"`
	Year               sql.NullInt32   `json:"year"`
	Kp                 sql.NullFloat64 `json:"kp"`
	Tmdb               sql.NullFloat64 `json:"tmdb"`
	FilmCritic         sql.NullFloat64 `json:"film_critic"`
	RussianFilmCritics sql.NullFloat64 `json:"russian_film_critics"`
}

func (q *Queries) GetMovie(ctx context.Context, kpID sql.NullInt32) (GetMovieRow, error) {
	row := q.db.QueryRowContext(ctx, getMovie, kpID)
	var i GetMovieRow
	err := row.Scan(
		&i.KpID,
		&i.ID,
		&i.RuName,
		&i.EnName,
		&i.MovieType,
		&i.Description,
		&i.Top250,
		&i.Budget,
		&i.Revenue,
		&i.TmdbID,
		&i.Year,
		&i.Kp,
		&i.Tmdb,
		&i.FilmCritic,
		&i.RussianFilmCritics,
	)
	return i, err
}

const saveAwards = `-- name: SaveAwards :exec
INSERT INTO awards(
    movie_id,
    award
) VALUES ($1,$2)
`

type SaveAwardsParams struct {
	MovieID sql.NullInt32  `json:"movie_id"`
	Award   sql.NullString `json:"award"`
}

func (q *Queries) SaveAwards(ctx context.Context, arg SaveAwardsParams) error {
	_, err := q.db.ExecContext(ctx, saveAwards, arg.MovieID, arg.Award)
	return err
}

const saveCast = `-- name: SaveCast :exec
INSERT INTO casts(
    movie_id,
    name,
    en_name,
    profession,
    description
) VALUES ($1,$2,$3,$4,$5)
`

type SaveCastParams struct {
	MovieID     sql.NullInt32  `json:"movie_id"`
	Name        sql.NullString `json:"name"`
	EnName      sql.NullString `json:"en_name"`
	Profession  sql.NullString `json:"profession"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) SaveCast(ctx context.Context, arg SaveCastParams) error {
	_, err := q.db.ExecContext(ctx, saveCast,
		arg.MovieID,
		arg.Name,
		arg.EnName,
		arg.Profession,
		arg.Description,
	)
	return err
}

const saveGenre = `-- name: SaveGenre :exec
INSERT INTO movie_genres (
    movie_id,
    genre_id
)
VALUES ($1,$2)
`

type SaveGenreParams struct {
	MovieID int32 `json:"movie_id"`
	GenreID int32 `json:"genre_id"`
}

func (q *Queries) SaveGenre(ctx context.Context, arg SaveGenreParams) error {
	_, err := q.db.ExecContext(ctx, saveGenre, arg.MovieID, arg.GenreID)
	return err
}

const saveMovie = `-- name: SaveMovie :one
INSERT INTO movies (
    kp_id,
    ru_name,
    en_name,
    movie_type,
    year,
    description,
    top250,
    budget,
    revenue,
    tmdb_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id
`

type SaveMovieParams struct {
	KpID        sql.NullInt32  `json:"kp_id"`
	RuName      sql.NullString `json:"ru_name"`
	EnName      sql.NullString `json:"en_name"`
	MovieType   sql.NullString `json:"movie_type"`
	Year        sql.NullInt32  `json:"year"`
	Description sql.NullString `json:"description"`
	Top250      sql.NullInt32  `json:"top250"`
	Budget      sql.NullInt32  `json:"budget"`
	Revenue     sql.NullInt32  `json:"revenue"`
	TmdbID      sql.NullInt32  `json:"tmdb_id"`
}

func (q *Queries) SaveMovie(ctx context.Context, arg SaveMovieParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, saveMovie,
		arg.KpID,
		arg.RuName,
		arg.EnName,
		arg.MovieType,
		arg.Year,
		arg.Description,
		arg.Top250,
		arg.Budget,
		arg.Revenue,
		arg.TmdbID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const saveRating = `-- name: SaveRating :exec
INSERT INTO ratings(
    movie_id,
    kp,
    tmdb,
    film_critic,
    russian_film_critics
) VALUES ($1,$2,$3,$4,$5)
`

type SaveRatingParams struct {
	MovieID            sql.NullInt32   `json:"movie_id"`
	Kp                 sql.NullFloat64 `json:"kp"`
	Tmdb               sql.NullFloat64 `json:"tmdb"`
	FilmCritic         sql.NullFloat64 `json:"film_critic"`
	RussianFilmCritics sql.NullFloat64 `json:"russian_film_critics"`
}

func (q *Queries) SaveRating(ctx context.Context, arg SaveRatingParams) error {
	_, err := q.db.ExecContext(ctx, saveRating,
		arg.MovieID,
		arg.Kp,
		arg.Tmdb,
		arg.FilmCritic,
		arg.RussianFilmCritics,
	)
	return err
}
