// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	kinopoisk "github.com/AliyaVV/MovieHub/internal/proxy/kinopoisk"

	mock "github.com/stretchr/testify/mock"

	model "github.com/AliyaVV/MovieHub/internal/model"
)

// KPClient is an autogenerated mock type for the KPClient type
type KPClient struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *KPClient) GetByID(ctx context.Context, id int) (kinopoisk.RespKPSearchID, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 kinopoisk.RespKPSearchID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (kinopoisk.RespKPSearchID, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) kinopoisk.RespKPSearchID); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(kinopoisk.RespKPSearchID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByTitle provides a mock function with given fields: ctx, title
func (_m *KPClient) SearchByTitle(ctx context.Context, title string) ([]*model.Movie_short, error) {
	ret := _m.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for SearchByTitle")
	}

	var r0 []*model.Movie_short
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Movie_short, error)); ok {
		return rf(ctx, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Movie_short); ok {
		r0 = rf(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Movie_short)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKPClient creates a new instance of KPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPClient {
	mock := &KPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
