// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/AliyaVV/MovieHub/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MovieRepository is an autogenerated mock type for the MovieRepository type
type MovieRepository struct {
	mock.Mock
}

// GetListMovies provides a mock function with given fields: ctx
func (_m *MovieRepository) GetListMovies(ctx context.Context) ([]model.Movie_short, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetListMovies")
	}

	var r0 []model.Movie_short
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Movie_short, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Movie_short); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Movie_short)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMovieById provides a mock function with given fields: ctx, id
func (_m *MovieRepository) GetMovieById(ctx context.Context, id int) (*model.Movie_ex, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieById")
	}

	var r0 *model.Movie_ex
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.Movie_ex, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.Movie_ex); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Movie_ex)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveMovie provides a mock function with given fields: ctx, movie
func (_m *MovieRepository) SaveMovie(ctx context.Context, movie *model.Movie_ex) (int32, error) {
	ret := _m.Called(ctx, movie)

	if len(ret) == 0 {
		panic("no return value specified for SaveMovie")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Movie_ex) (int32, error)); ok {
		return rf(ctx, movie)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Movie_ex) int32); ok {
		r0 = rf(ctx, movie)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Movie_ex) error); ok {
		r1 = rf(ctx, movie)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TestDirectInsert provides a mock function with given fields: ctx
func (_m *MovieRepository) TestDirectInsert(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TestDirectInsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMovieRepository creates a new instance of MovieRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieRepository {
	mock := &MovieRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
