// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SearchLogger is an autogenerated mock type for the SearchLogger type
type SearchLogger struct {
	mock.Mock
}

// Log provides a mock function with given fields: ctx, query, resultCount
func (_m *SearchLogger) Log(ctx context.Context, query string, resultCount int) error {
	ret := _m.Called(ctx, query, resultCount)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, query, resultCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSearchLogger creates a new instance of SearchLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchLogger {
	mock := &SearchLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
