// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	tmdbmapper "github.com/AliyaVV/MovieHub/internal/mapper/tmdbmapper"
)

// TMDBClient is an autogenerated mock type for the TMDBClient type
type TMDBClient struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TMDBClient) GetByID(ctx context.Context, id int) (*tmdbmapper.Tmdb_movie_midl, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *tmdbmapper.Tmdb_movie_midl
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*tmdbmapper.Tmdb_movie_midl, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *tmdbmapper.Tmdb_movie_midl); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tmdbmapper.Tmdb_movie_midl)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByTitle provides a mock function with given fields: ctx, title
func (_m *TMDBClient) SearchByTitle(ctx context.Context, title string) ([]*tmdbmapper.Tmdb_movie_midl, error) {
	ret := _m.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for SearchByTitle")
	}

	var r0 []*tmdbmapper.Tmdb_movie_midl
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*tmdbmapper.Tmdb_movie_midl, error)); ok {
		return rf(ctx, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*tmdbmapper.Tmdb_movie_midl); ok {
		r0 = rf(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tmdbmapper.Tmdb_movie_midl)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTMDBClient creates a new instance of TMDBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTMDBClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TMDBClient {
	mock := &TMDBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
