// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: api/movie.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{0}
}

type MovieShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Runame        string                 `protobuf:"bytes,2,opt,name=runame,proto3" json:"runame,omitempty"`
	Enname        string                 `protobuf:"bytes,3,opt,name=enname,proto3" json:"enname,omitempty"`
	Movietype     string                 `protobuf:"bytes,4,opt,name=movietype,proto3" json:"movietype,omitempty"`
	Movieyear     int32                  `protobuf:"varint,5,opt,name=movieyear,proto3" json:"movieyear,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieShort) Reset() {
	*x = MovieShort{}
	mi := &file_api_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieShort) ProtoMessage() {}

func (x *MovieShort) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieShort.ProtoReflect.Descriptor instead.
func (*MovieShort) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{1}
}

func (x *MovieShort) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MovieShort) GetRuname() string {
	if x != nil {
		return x.Runame
	}
	return ""
}

func (x *MovieShort) GetEnname() string {
	if x != nil {
		return x.Enname
	}
	return ""
}

func (x *MovieShort) GetMovietype() string {
	if x != nil {
		return x.Movietype
	}
	return ""
}

func (x *MovieShort) GetMovieyear() int32 {
	if x != nil {
		return x.Movieyear
	}
	return 0
}

type MovieEx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Poster        string                 `protobuf:"bytes,3,opt,name=poster,proto3" json:"poster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieEx) Reset() {
	*x = MovieEx{}
	mi := &file_api_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieEx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieEx) ProtoMessage() {}

func (x *MovieEx) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieEx.ProtoReflect.Descriptor instead.
func (*MovieEx) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{2}
}

func (x *MovieEx) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MovieEx) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MovieEx) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

type CreateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *MovieShort            `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieRequest) Reset() {
	*x = CreateMovieRequest{}
	mi := &file_api_movie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieRequest) ProtoMessage() {}

func (x *CreateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieRequest.ProtoReflect.Descriptor instead.
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMovieRequest) GetMovie() *MovieShort {
	if x != nil {
		return x.Movie
	}
	return nil
}

type GetMovieByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieByIdRequest) Reset() {
	*x = GetMovieByIdRequest{}
	mi := &file_api_movie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIdRequest) ProtoMessage() {}

func (x *GetMovieByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMovieByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{4}
}

func (x *GetMovieByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MovieExResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *MovieEx               `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieExResponse) Reset() {
	*x = MovieExResponse{}
	mi := &file_api_movie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieExResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieExResponse) ProtoMessage() {}

func (x *MovieExResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieExResponse.ProtoReflect.Descriptor instead.
func (*MovieExResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{5}
}

func (x *MovieExResponse) GetMovie() *MovieEx {
	if x != nil {
		return x.Movie
	}
	return nil
}

type MovieShortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *MovieShort            `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieShortResponse) Reset() {
	*x = MovieShortResponse{}
	mi := &file_api_movie_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieShortResponse) ProtoMessage() {}

func (x *MovieShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieShortResponse.ProtoReflect.Descriptor instead.
func (*MovieShortResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{6}
}

func (x *MovieShortResponse) GetMovie() *MovieShort {
	if x != nil {
		return x.Movie
	}
	return nil
}

type MovieShortListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*MovieShort          `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieShortListResponse) Reset() {
	*x = MovieShortListResponse{}
	mi := &file_api_movie_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieShortListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieShortListResponse) ProtoMessage() {}

func (x *MovieShortListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieShortListResponse.ProtoReflect.Descriptor instead.
func (*MovieShortListResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{7}
}

func (x *MovieShortListResponse) GetMovies() []*MovieShort {
	if x != nil {
		return x.Movies
	}
	return nil
}

var File_api_movie_proto protoreflect.FileDescriptor

const file_api_movie_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/movie.proto\x12\x05movie\"\a\n" +
	"\x05Empty\"\x88\x01\n" +
	"\n" +
	"MovieShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06runame\x18\x02 \x01(\tR\x06runame\x12\x16\n" +
	"\x06enname\x18\x03 \x01(\tR\x06enname\x12\x1c\n" +
	"\tmovietype\x18\x04 \x01(\tR\tmovietype\x12\x1c\n" +
	"\tmovieyear\x18\x05 \x01(\x05R\tmovieyear\"S\n" +
	"\aMovieEx\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06poster\x18\x03 \x01(\tR\x06poster\"=\n" +
	"\x12CreateMovieRequest\x12'\n" +
	"\x05movie\x18\x01 \x01(\v2\x11.movie.MovieShortR\x05movie\"%\n" +
	"\x13GetMovieByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"7\n" +
	"\x0fMovieExResponse\x12$\n" +
	"\x05movie\x18\x01 \x01(\v2\x0e.movie.MovieExR\x05movie\"=\n" +
	"\x12MovieShortResponse\x12'\n" +
	"\x05movie\x18\x01 \x01(\v2\x11.movie.MovieShortR\x05movie\"C\n" +
	"\x16MovieShortListResponse\x12)\n" +
	"\x06movies\x18\x01 \x03(\v2\x11.movie.MovieShortR\x06movies2\xd1\x01\n" +
	"\fMovieService\x12C\n" +
	"\vCreateMovie\x12\x19.movie.CreateMovieRequest\x1a\x19.movie.MovieShortResponse\x12B\n" +
	"\fGetMovieById\x12\x1a.movie.GetMovieByIdRequest\x1a\x16.movie.MovieExResponse\x128\n" +
	"\tGetMovies\x12\f.movie.Empty\x1a\x1d.movie.MovieShortListResponseB%Z#github.com/AliyaVV/MovieHub/grpc/pbb\x06proto3"

var (
	file_api_movie_proto_rawDescOnce sync.Once
	file_api_movie_proto_rawDescData []byte
)

func file_api_movie_proto_rawDescGZIP() []byte {
	file_api_movie_proto_rawDescOnce.Do(func() {
		file_api_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_movie_proto_rawDesc), len(file_api_movie_proto_rawDesc)))
	})
	return file_api_movie_proto_rawDescData
}

var file_api_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_movie_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: movie.Empty
	(*MovieShort)(nil),             // 1: movie.MovieShort
	(*MovieEx)(nil),                // 2: movie.MovieEx
	(*CreateMovieRequest)(nil),     // 3: movie.CreateMovieRequest
	(*GetMovieByIdRequest)(nil),    // 4: movie.GetMovieByIdRequest
	(*MovieExResponse)(nil),        // 5: movie.MovieExResponse
	(*MovieShortResponse)(nil),     // 6: movie.MovieShortResponse
	(*MovieShortListResponse)(nil), // 7: movie.MovieShortListResponse
}
var file_api_movie_proto_depIdxs = []int32{
	1, // 0: movie.CreateMovieRequest.movie:type_name -> movie.MovieShort
	2, // 1: movie.MovieExResponse.movie:type_name -> movie.MovieEx
	1, // 2: movie.MovieShortResponse.movie:type_name -> movie.MovieShort
	1, // 3: movie.MovieShortListResponse.movies:type_name -> movie.MovieShort
	3, // 4: movie.MovieService.CreateMovie:input_type -> movie.CreateMovieRequest
	4, // 5: movie.MovieService.GetMovieById:input_type -> movie.GetMovieByIdRequest
	0, // 6: movie.MovieService.GetMovies:input_type -> movie.Empty
	6, // 7: movie.MovieService.CreateMovie:output_type -> movie.MovieShortResponse
	5, // 8: movie.MovieService.GetMovieById:output_type -> movie.MovieExResponse
	7, // 9: movie.MovieService.GetMovies:output_type -> movie.MovieShortListResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_movie_proto_init() }
func file_api_movie_proto_init() {
	if File_api_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_movie_proto_rawDesc), len(file_api_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_movie_proto_goTypes,
		DependencyIndexes: file_api_movie_proto_depIdxs,
		MessageInfos:      file_api_movie_proto_msgTypes,
	}.Build()
	File_api_movie_proto = out.File
	file_api_movie_proto_goTypes = nil
	file_api_movie_proto_depIdxs = nil
}
