basePath: /
definitions:
  model.Cast:
    properties:
      description:
        type: string
      enName:
        type: string
      name:
        type: string
      profession:
        type: string
    type: object
  model.ExternalId:
    properties:
      tmdb:
        type: integer
    type: object
  model.Movie_ex:
    properties:
      awards:
        items:
          type: string
        type: array
      budget:
        type: integer
      cast:
        items:
          $ref: '#/definitions/model.Cast'
        type: array
      country:
        items:
          type: string
        type: array
      description:
        type: string
      enName:
        type: string
      externalId:
        $ref: '#/definitions/model.ExternalId'
      genres:
        items:
          type: string
        type: array
      id:
        type: integer
      movieType:
        type: string
      movieYear:
        type: integer
      poster:
        type: string
      ratings:
        $ref: '#/definitions/model.Ratings'
      revenue:
        type: integer
      runame:
        type: string
      seasons:
        items:
          $ref: '#/definitions/model.Seasons'
        type: array
      source:
        $ref: '#/definitions/model.Source'
      top250:
        type: integer
    type: object
  model.Movie_short:
    properties:
      enName:
        type: string
      externalId:
        $ref: '#/definitions/model.ExternalId'
      genres:
        items:
          type: string
        type: array
      id:
        type: integer
      movieType:
        type: string
      movieYear:
        type: integer
      ratings:
        $ref: '#/definitions/model.Ratings'
      runame:
        type: string
    type: object
  model.Ratings:
    properties:
      filmCritic:
        format: float64
        type: number
      kp:
        format: float64
        type: number
      russianFilmCritics:
        format: float64
        type: number
      tmdb:
        format: float64
        type: number
    type: object
  model.Seasons:
    properties:
      episodesCount:
        type: integer
      number:
        type: integer
    type: object
  model.Source:
    properties:
      kphd:
        type: boolean
      tmdb:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для работы с фильмами
  title: MovieHub API
  version: "1.0"
paths:
  /movies/{id}:
    get:
      consumes:
      - application/json
      description: Возвращает полную информацию о фильме
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Movie_ex'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Поиск фильма по ID
      tags:
      - movies
  /movies/list:
    get:
      consumes:
      - application/json
      description: Возвращает все фильмы из БД
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Movie_short'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить список фильмов
      tags:
      - movies
  /movies/search:
    get:
      consumes:
      - application/json
      description: Возвращает список фильмов
      parameters:
      - description: Movie title
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Movie_short'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Поиск фильма по названию
      tags:
      - movies
swagger: "2.0"
